// @generated by codegen_tests.py -- DO NOT EDIT
import { describe, it, expect } from "vitest";
import { transpile } from "../../src/index.js";

const DIALECT = "dune";

function validateIdentity(sql: string, writeSql?: string): void {
  const result = transpile(sql, { readDialect: DIALECT, writeDialect: DIALECT })[0];
  expect(result).toBe(writeSql ?? sql);
}

describe("Dune: dune", () => {
  it("CAST(x AS INT256)", () => {
    validateIdentity("CAST(x AS INT256)");
  });
  it("CAST(x AS UINT256)", () => {
    validateIdentity("CAST(x AS UINT256)");
  });
  it.todo("test_dune: parse_one call");
  it.todo("dune -> dune: SELECT X'deadbeef' (unsupported syntax)");
  it.todo("postgres -> dune: SELECT x'deadbeef' (unsupported syntax)");
  it.todo("trino -> dune: SELECT X'deadbeef' (unsupported syntax)");
  it("dune -> dune: SELECT 0xdeadbeef", () => {
    const result = transpile("SELECT 0xdeadbeef", { readDialect: DIALECT, writeDialect: "dune" })[0];
    expect(result).toBe("SELECT 0xdeadbeef");
  });
  it.todo("dune -> postgres: SELECT 0xdeadbeef (unsupported syntax)");
  it.todo("dune -> trino: SELECT 0xdeadbeef (unsupported syntax)");
  it.todo("test_dune: parse_one call (2)");
  it.todo("dune -> dune: SELECT X'deadbeefdead' (unsupported syntax)");
  it.todo("postgres -> dune: SELECT x'deadbeefdead' (unsupported syntax)");
  it.todo("trino -> dune: SELECT X'deadbeefdead' (unsupported syntax)");
  it("dune -> dune: SELECT 0xdeadbeefdead", () => {
    const result = transpile("SELECT 0xdeadbeefdead", { readDialect: DIALECT, writeDialect: "dune" })[0];
    expect(result).toBe("SELECT 0xdeadbeefdead");
  });
  it.todo("dune -> postgres: SELECT 0xdeadbeefdead (unsupported syntax)");
  it.todo("dune -> trino: SELECT 0xdeadbeefdead (unsupported syntax)");
  it.todo("test_dune: parse_one call (3)");
  it.todo("dune -> dune: SELECT X'deadbeefdeadbeef' (unsupported syntax)");
  it.todo("postgres -> dune: SELECT x'deadbeefdeadbeef' (unsupported syntax)");
  it.todo("trino -> dune: SELECT X'deadbeefdeadbeef' (unsupported syntax)");
  it("dune -> dune: SELECT 0xdeadbeefdeadbeef", () => {
    const result = transpile("SELECT 0xdeadbeefdeadbeef", { readDialect: DIALECT, writeDialect: "dune" })[0];
    expect(result).toBe("SELECT 0xdeadbeefdeadbeef");
  });
  it.todo("dune -> postgres: SELECT 0xdeadbeefdeadbeef (unsupported syntax)");
  it.todo("dune -> trino: SELECT 0xdeadbeefdeadbeef (unsupported syntax)");
  it.todo("test_dune: parse_one call (4)");
  it.todo("dune -> dune: SELECT X'deadbeefdeadbeefde' (unsupported syntax)");
  it.todo("postgres -> dune: SELECT x'deadbeefdeadbeefde' (unsupported syntax)");
  it.todo("trino -> dune: SELECT X'deadbeefdeadbeefde' (unsupported syntax)");
  it("dune -> dune: SELECT 0xdeadbeefdeadbeefde", () => {
    const result = transpile("SELECT 0xdeadbeefdeadbeefde", { readDialect: DIALECT, writeDialect: "dune" })[0];
    expect(result).toBe("SELECT 0xdeadbeefdeadbeefde");
  });
  it.todo("dune -> postgres: SELECT 0xdeadbeefdeadbeefde (unsupported syntax)");
  it.todo("dune -> trino: SELECT 0xdeadbeefdeadbeefde (unsupported syntax)");
  it.todo("test_dune: parse_one call (5)");
  it.todo("dune -> dune: SELECT X'deadbeefdeadbeefdead' (unsupported syntax)");
  it.todo("postgres -> dune: SELECT x'deadbeefdeadbeefdead' (unsupported syntax)");
  it.todo("trino -> dune: SELECT X'deadbeefdeadbeefdead' (unsupported syntax)");
  it("dune -> dune: SELECT 0xdeadbeefdeadbeefdead", () => {
    const result = transpile("SELECT 0xdeadbeefdeadbeefdead", { readDialect: DIALECT, writeDialect: "dune" })[0];
    expect(result).toBe("SELECT 0xdeadbeefdeadbeefdead");
  });
  it.todo("dune -> postgres: SELECT 0xdeadbeefdeadbeefdead (unsupported syntax)");
  it.todo("dune -> trino: SELECT 0xdeadbeefdeadbeefdead (unsupported syntax)");
  it.todo("test_dune: parse_one call (6)");
  it.todo("dune -> dune: SELECT X'deadbeefdeadbeefdeadbeef' (unsupported syntax)");
  it.todo("postgres -> dune: SELECT x'deadbeefdeadbeefdeadbeef' (unsupported syntax)");
  it.todo("trino -> dune: SELECT X'deadbeefdeadbeefdeadbeef' (unsupported syntax)");
  it("dune -> dune: SELECT 0xdeadbeefdeadbeefdeadbeef", () => {
    const result = transpile("SELECT 0xdeadbeefdeadbeefdeadbeef", { readDialect: DIALECT, writeDialect: "dune" })[0];
    expect(result).toBe("SELECT 0xdeadbeefdeadbeefdeadbeef");
  });
  it.todo("dune -> postgres: SELECT 0xdeadbeefdeadbeefdeadbeef (unsupported syntax)");
  it.todo("dune -> trino: SELECT 0xdeadbeefdeadbeefdeadbeef (unsupported syntax)");
  it.todo("test_dune: parse_one call (7)");
  it.todo("dune -> dune: SELECT X'deadbeefdeadbeefdeadbeefdeadbeef' (unsupported syntax)");
  it.todo("postgres -> dune: SELECT x'deadbeefdeadbeefdeadbeefdeadbeef' (unsupported syntax)");
  it.todo("trino -> dune: SELECT X'deadbeefdeadbeefdeadbeefdeadbeef' (unsupported syntax)");
  it("dune -> dune: SELECT 0xdeadbeefdeadbeefdeadbeefdeadbeef", () => {
    const result = transpile("SELECT 0xdeadbeefdeadbeefdeadbeefdeadbeef", { readDialect: DIALECT, writeDialect: "dune" })[0];
    expect(result).toBe("SELECT 0xdeadbeefdeadbeefdeadbeefdeadbeef");
  });
  it.todo("dune -> postgres: SELECT 0xdeadbeefdeadbeefdeadbeefdeadbeef (unsupported syntax)");
  it.todo("dune -> trino: SELECT 0xdeadbeefdeadbeefdeadbeefdeadbeef (unsupported syntax)");
});
