// @generated by codegen_tests.py -- DO NOT EDIT
import { describe, it, expect } from "vitest";
import { transpile } from "../../src/index.js";

const DIALECT = "risingwave";

function validateIdentity(sql: string, writeSql?: string): void {
  const result = transpile(sql, { readDialect: DIALECT, writeDialect: DIALECT })[0];
  expect(result).toBe(writeSql ?? sql);
}

describe("Risingwave: risingwave", () => {
  it.todo(" -> risingwave: SELECT a FROM tbl FOR UPDATE (unsupported clause)");
  it.todo("CREATE SOURCE from_kafka (*, gen_i32_field INT AS int32_field + 2, ... (DDL/DML not supported)");
  it.todo("CREATE SINK my_sink AS SELECT * FROM A WITH (connector='kafka', top... (DDL/DML not supported)");
  it.todo("WITH t1 AS MATERIALIZED (SELECT 1), t2 AS NOT MATERIALIZED (SELECT ... (unsupported syntax)");
});

describe("Risingwave: datatypes", () => {
  it("SELECT CAST(NULL AS MAP(VARCHAR, INT)) AS map_column", () => {
    validateIdentity("SELECT CAST(NULL AS MAP(VARCHAR, INT)) AS map_column");
  });
  it.todo("SELECT NULL::MAP<VARCHAR, INT> AS map_column (unsupported syntax)");
  it.todo("CREATE TABLE t (map_col MAP(VARCHAR, INT)) (DDL/DML not supported)");
  it.todo("CREATE TABLE t (map_col MAP<VARCHAR, INT>) (DDL/DML not supported)");
});
