// @generated by codegen_tests.py -- DO NOT EDIT
import { describe, it, expect } from "vitest";
import { transpile } from "../../src/index.js";

const DIALECT = "drill";

function validateIdentity(sql: string, writeSql?: string): void {
  const result = transpile(sql, { readDialect: DIALECT, writeDialect: DIALECT })[0];
  expect(result).toBe(writeSql ?? sql);
}

describe("Drill: drill", () => {
  it("SELECT * FROM table(dfs.`test_data.xlsx`(type => 'excel', sheetName => 'secondSheet'))", () => {
    validateIdentity("SELECT * FROM table(dfs.`test_data.xlsx`(type => 'excel', sheetName => 'secondSheet'))");
  });
  it.todo("SELECT * FROM (SELECT * FROM t) PIVOT(avg(c1) AS ac1 FOR c2 IN ('V'... (unsupported clause)");
  it.todo("drill -> drill: SELECT '2021-01-01' + INTERVAL 1 MONTH (unsupported syntax)");
  it.todo("drill -> mysql: SELECT '2021-01-01' + INTERVAL 1 MONTH (unsupported syntax)");
});

describe("Drill: analyze", () => {
  it.todo("ANALYZE TABLE tbl COMPUTE STATISTICS (command not supported)");
  it.todo("ANALYZE TABLE tbl COMPUTE STATISTICS SAMPLE 5 PERCENT (command not supported)");
});
