// @generated by codegen_tests.py -- DO NOT EDIT
import { describe, it, expect } from "vitest";
import { transpile } from "../../src/index.js";

const DIALECT = "fabric";

function validateIdentity(sql: string, writeSql?: string): void {
  const result = transpile(sql, { readDialect: DIALECT, writeDialect: DIALECT })[0];
  expect(result).toBe(writeSql ?? sql);
}

describe("Fabric: type_mappings", () => {
  it("CAST(x AS BOOLEAN) -> CAST(x AS BIT)", () => {
    validateIdentity("CAST(x AS BOOLEAN)", "CAST(x AS BIT)");
  });
  it("CAST(x AS DATE) -> CAST(x AS DATE)", () => {
    validateIdentity("CAST(x AS DATE)", "CAST(x AS DATE)");
  });
  it("CAST(x AS DATETIME) -> CAST(x AS DATETIME2(6))", () => {
    validateIdentity("CAST(x AS DATETIME)", "CAST(x AS DATETIME2(6))");
  });
  it("CAST(x AS DECIMAL) -> CAST(x AS DECIMAL)", () => {
    validateIdentity("CAST(x AS DECIMAL)", "CAST(x AS DECIMAL)");
  });
  it("CAST(x AS DOUBLE) -> CAST(x AS FLOAT)", () => {
    validateIdentity("CAST(x AS DOUBLE)", "CAST(x AS FLOAT)");
  });
  it("CAST(x AS IMAGE) -> CAST(x AS VARBINARY)", () => {
    validateIdentity("CAST(x AS IMAGE)", "CAST(x AS VARBINARY)");
  });
  it("CAST(x AS INT) -> CAST(x AS INT)", () => {
    validateIdentity("CAST(x AS INT)", "CAST(x AS INT)");
  });
  it("CAST(x AS JSON) -> CAST(x AS VARCHAR)", () => {
    validateIdentity("CAST(x AS JSON)", "CAST(x AS VARCHAR)");
  });
  it("CAST(x AS MONEY) -> CAST(x AS DECIMAL)", () => {
    validateIdentity("CAST(x AS MONEY)", "CAST(x AS DECIMAL)");
  });
  it("CAST(x AS NCHAR) -> CAST(x AS CHAR)", () => {
    validateIdentity("CAST(x AS NCHAR)", "CAST(x AS CHAR)");
  });
  it("CAST(x AS NVARCHAR) -> CAST(x AS VARCHAR)", () => {
    validateIdentity("CAST(x AS NVARCHAR)", "CAST(x AS VARCHAR)");
  });
  it("CAST(x AS ROWVERSION) -> CAST(x AS ROWVERSION)", () => {
    validateIdentity("CAST(x AS ROWVERSION)", "CAST(x AS ROWVERSION)");
  });
  it("CAST(x AS SMALLDATETIME) -> CAST(x AS DATETIME2(6))", () => {
    validateIdentity("CAST(x AS SMALLDATETIME)", "CAST(x AS DATETIME2(6))");
  });
  it("CAST(x AS SMALLMONEY) -> CAST(x AS DECIMAL)", () => {
    validateIdentity("CAST(x AS SMALLMONEY)", "CAST(x AS DECIMAL)");
  });
  it("CAST(x AS TEXT) -> CAST(x AS VARCHAR(MAX))", () => {
    validateIdentity("CAST(x AS TEXT)", "CAST(x AS VARCHAR(MAX))");
  });
  it.todo("CAST(x AS TIMESTAMP) (unsupported syntax)");
  it("CAST(x AS TIMESTAMPNTZ) -> CAST(x AS DATETIME2(6))", () => {
    validateIdentity("CAST(x AS TIMESTAMPNTZ)", "CAST(x AS DATETIME2(6))");
  });
  it("CAST(x AS TINYINT) -> CAST(x AS SMALLINT)", () => {
    validateIdentity("CAST(x AS TINYINT)", "CAST(x AS SMALLINT)");
  });
  it("CAST(x AS UTINYINT) -> CAST(x AS SMALLINT)", () => {
    validateIdentity("CAST(x AS UTINYINT)", "CAST(x AS SMALLINT)");
  });
  it("CAST(x AS UUID) -> CAST(x AS UNIQUEIDENTIFIER)", () => {
    validateIdentity("CAST(x AS UUID)", "CAST(x AS UNIQUEIDENTIFIER)");
  });
  it("CAST(x AS VARIANT) -> CAST(x AS SQL_VARIANT)", () => {
    validateIdentity("CAST(x AS VARIANT)", "CAST(x AS SQL_VARIANT)");
  });
  it("CAST(x AS XML) -> CAST(x AS VARCHAR)", () => {
    validateIdentity("CAST(x AS XML)", "CAST(x AS VARCHAR)");
  });
});

describe("Fabric: precision_capping", () => {
  it("CAST(x AS TIME) -> CAST(x AS TIME(6))", () => {
    validateIdentity("CAST(x AS TIME)", "CAST(x AS TIME(6))");
  });
  it("CAST(x AS DATETIME2) -> CAST(x AS DATETIME2(6))", () => {
    validateIdentity("CAST(x AS DATETIME2)", "CAST(x AS DATETIME2(6))");
  });
  it("CAST(x AS TIME(3)) -> CAST(x AS TIME(3))", () => {
    validateIdentity("CAST(x AS TIME(3))", "CAST(x AS TIME(3))");
  });
  it("CAST(x AS DATETIME2(3)) -> CAST(x AS DATETIME2(3))", () => {
    validateIdentity("CAST(x AS DATETIME2(3))", "CAST(x AS DATETIME2(3))");
  });
  it("CAST(x AS TIME(6)) -> CAST(x AS TIME(6))", () => {
    validateIdentity("CAST(x AS TIME(6))", "CAST(x AS TIME(6))");
  });
  it("CAST(x AS DATETIME2(6)) -> CAST(x AS DATETIME2(6))", () => {
    validateIdentity("CAST(x AS DATETIME2(6))", "CAST(x AS DATETIME2(6))");
  });
  it("CAST(x AS TIME(7)) -> CAST(x AS TIME(6))", () => {
    validateIdentity("CAST(x AS TIME(7))", "CAST(x AS TIME(6))");
  });
  it("CAST(x AS DATETIME2(7)) -> CAST(x AS DATETIME2(6))", () => {
    validateIdentity("CAST(x AS DATETIME2(7))", "CAST(x AS DATETIME2(6))");
  });
  it("CAST(x AS TIME(9)) -> CAST(x AS TIME(6))", () => {
    validateIdentity("CAST(x AS TIME(9))", "CAST(x AS TIME(6))");
  });
  it("CAST(x AS DATETIME2(9)) -> CAST(x AS DATETIME2(6))", () => {
    validateIdentity("CAST(x AS DATETIME2(9))", "CAST(x AS DATETIME2(6))");
  });
});

describe("Fabric: timestamptz_without_at_time_zone", () => {
  it.todo("CAST(x AS TIMESTAMPTZ) (unsupported syntax)");
  it("CAST(x AS TIMESTAMPTZ(3)) -> CAST(x AS DATETIME2(3))", () => {
    validateIdentity("CAST(x AS TIMESTAMPTZ(3))", "CAST(x AS DATETIME2(3))");
  });
  it("CAST(x AS TIMESTAMPTZ(6)) -> CAST(x AS DATETIME2(6))", () => {
    validateIdentity("CAST(x AS TIMESTAMPTZ(6))", "CAST(x AS DATETIME2(6))");
  });
  it("CAST(x AS TIMESTAMPTZ(9)) -> CAST(x AS DATETIME2(6))", () => {
    validateIdentity("CAST(x AS TIMESTAMPTZ(9))", "CAST(x AS DATETIME2(6))");
  });
});

describe("Fabric: timestamptz_with_at_time_zone", () => {
  it.todo("CAST(x AS TIMESTAMPTZ) AT TIME ZONE 'Pacific Standard Time' (unsupported syntax)");
  it.todo("CAST(x AS TIMESTAMPTZ(3)) AT TIME ZONE 'Pacific Standard Time' (unsupported syntax)");
  it.todo("CAST(x AS TIMESTAMPTZ(6)) AT TIME ZONE 'Pacific Standard Time' (unsupported syntax)");
  it.todo("CAST(x AS TIMESTAMPTZ(9)) AT TIME ZONE 'Pacific Standard Time' (unsupported syntax)");
});

describe("Fabric: unix_to_time", () => {
  it("UNIX_TO_TIME(column) -> DATEADD(MICROSECONDS, CAST(ROUND(column * 1e6, 0) AS BIGINT), C...", () => {
    validateIdentity("UNIX_TO_TIME(column)", "DATEADD(MICROSECONDS, CAST(ROUND(column * 1e6, 0) AS BIGINT), CAST('1970-01-01' AS DATETIME2(6)))");
  });
});

describe("Fabric: varchar_precision_inference", () => {
  it.todo("CREATE TABLE t (col VARCHAR) (DDL/DML not supported)");
  it.todo("CREATE TABLE t (col VARCHAR(50)) (DDL/DML not supported)");
  it.todo("CREATE TABLE t (col CHAR) (DDL/DML not supported)");
  it.todo("CREATE TABLE t (col CHAR(10)) (DDL/DML not supported)");
  it.todo("CREATE TABLE t (col VARCHAR(MAX)) (DDL/DML not supported)");
  it.todo("CREATE TABLE t (col CHAR(MAX)) (DDL/DML not supported)");
});
